stages:
  - verify
  - build

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: never

verify-frontend:
  stage: verify
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline --legacy-peer-deps
  script:
    - npm run lint
    - npm test

verify-rust:
  stage: verify
  image: rust:latest
  cache:
    key: "rust-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - src-tauri/target/
      - .cargo/
      - apt-cache/
  before_script:
    - export CARGO_HOME="${CI_PROJECT_DIR}/.cargo"
    - mkdir -p apt-cache
    - rm -rf /var/cache/apt/archives && ln -s "${CI_PROJECT_DIR}/apt-cache" /var/cache/apt/archives
    - apt-get update && apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf
  script:
    - cargo check --manifest-path src-tauri/Cargo.toml
    - cargo test --manifest-path src-tauri/Cargo.toml

build-frontend:
  stage: build
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline --legacy-peer-deps
  script:
    - npm run build
